Namespace IInterface
    Public Interface IEmployee
        Property job_job_company As String '"IDCSI",
        Property job_job_title As String '"PROGRAMMER",
        Property idno As String '"DYYJ",
        Property last_name As String '"FERNANDEZ",
        Property first_name As String '"SEAN IVAN",
        Property middle_name As String '"MARTINEZ",
        Property tin As String '"325-824-533",
        Property sss As String '"34-5660025-5",
        Property philhealth As String '"01-025901475-7",
        Property pagibig As String '"",
        Property department As String '"SOFTWARE",
        Property heads_idno As String '"D526,LS50",
        Property divisions As String '"ADMINISTRATIVE",
        Property jobcode As String '"S",
        Property jobrole As String '"NON-PROD",
        Property job_location As String '"MANILA",
        Property employment_status As String '"REGULAR",
        Property job_category As String '"INFORMATION TECHNOLOGY",
        Property leave_replenishment_date As String '"2021-07-06",
        Property joined_date As String '"2016-01-05",
        Property emp_con_start_date As String '"2016-07-06",
        Property job_remarks As String '"",
        Property jobnote As String '"",
        Property bank_name As String '"UCPB",
        Property bank_category As String '"CASHCARD",
        Property effectivity_date As String '"2016-01-30",
        Property rate As String '"1",
        Property status As String '"ABOVE MINIMUM",
        Property account_number As String '"",
        Property card_number As String '"4574535000946148",
        Property payroll_code As String '"P1ACCARD",
        Property remarks_salary As String '"",
        Property atm_status As String '"",
        Property timesheet_guide_remarks As String '"FIX96/NO OT/NO ALLOW/NO ND",
        Property work_status As String '"REGULAR",
        Property ot_flag As String '"0",
        Property nd_flag As String '"0",
        Property allowance_flag As String '"0",
        Property in_flag As String '"0"
    End Interface

End Namespace
